import type { IconKey } from '@ritmo/shared'
import {
  Apple,
  BedDouble,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Code,
  Coffee,
  Droplets,
  Dumbbell,
  Flame,
  Footprints,
  GraduationCap,
  Heart,
  Languages,
  Leaf,
  Moon,
  Music,
  Pencil,
  PhoneOff,
  Pill,
  Salad,
  ShowerHead,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Target,
  Timer,
  Trophy,
  Wallet,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

/** O `Record<IconKey, …>` garante em tempo de compilação que todo ícone do shared tem componente. */
export const ICONS: Record<IconKey, LucideIcon> = {
  dumbbell: Dumbbell,
  book: BookOpen,
  droplets: Droplets,
  moon: Moon,
  sun: Sun,
  coffee: Coffee,
  brain: Brain,
  heart: Heart,
  apple: Apple,
  bike: Bike,
  footprints: Footprints,
  pencil: Pencil,
  music: Music,
  code: Code,
  wallet: Wallet,
  target: Target,
  flame: Flame,
  sparkles: Sparkles,
  bed: BedDouble,
  smile: Smile,
  languages: Languages,
  leaf: Leaf,
  briefcase: Briefcase,
  graduation: GraduationCap,
  salad: Salad,
  pill: Pill,
  timer: Timer,
  'phone-off': PhoneOff,
  shower: ShowerHead,
  sprout: Sprout,
  trophy: Trophy,
  star: Star,
}

export const ICON_LABELS: Record<IconKey, string> = {
  dumbbell: 'Treino',
  book: 'Leitura',
  droplets: 'Água',
  moon: 'Sono',
  sun: 'Manhã',
  coffee: 'Café',
  brain: 'Mente',
  heart: 'Saúde',
  apple: 'Alimentação',
  bike: 'Bicicleta',
  footprints: 'Caminhada',
  pencil: 'Escrita',
  music: 'Música',
  code: 'Código',
  wallet: 'Finanças',
  target: 'Foco',
  flame: 'Energia',
  sparkles: 'Brilho',
  bed: 'Descanso',
  smile: 'Bem-estar',
  languages: 'Idiomas',
  leaf: 'Natureza',
  briefcase: 'Trabalho',
  graduation: 'Estudos',
  salad: 'Dieta',
  pill: 'Remédio',
  timer: 'Tempo',
  'phone-off': 'Sem celular',
  shower: 'Banho',
  sprout: 'Crescimento',
  trophy: 'Conquista',
  star: 'Estrela',
}
